### ISSUE TITLE
enhance sshtunnel Script for Dynamic IP Handling and Alias Management

### ISSUE THREAD

**Issue by hiroTochigi** [treehouses/luftballon#48]
We propose several enhancements to the sshtunnel script to better handle dynamic IP addresses and alias management:

1. Dynamic Configuration Support: Modify the script to use variable names instead of static IP addresses in /etc/tunnel for more flexibility.
2. Alias Management in /etc/hosts: Automatically add and update IP addresses and their corresponding aliases in /etc/hosts.
3. Automatic IP Updates: Detect when a device (referred to as "balloon" but meaning a device with a dynamic IP) restarts and receives a new IP, updating /etc/hosts and /etc/tunnel accordingly.
4. Cleanup Mechanism: Implement functionality to remove an alias and its IP address from /etc/hosts and the corresponding configuration from /etc/tunnel when no longer needed.

**Comment by dogi** [comment]
#47
