### ISSUE TITLE
running up twice ...

### ISSUE THREAD

**Issue by dogi** [treehouses/luftballon#57]
```
./main.sh aws up
aws-cli/1.19.1 Python/3.9.2 Linux/5.15.61-v8+ botocore/1.20.0

An error occurred (InvalidKeyPair.Duplicate) when calling the ImportKeyPair operation: The keypair already exists
```

**Comment by hiroTochigi** [comment]
### Check SSH Key:

- Modify the script to verify if the specified SSH key already exists on AWS.
- If the key does not exist, bring it.

### Check Security Group:

- Modify the script to verify if the specified Security Group exists.
- If the group does not exist, create it.

### Check EC2 Instance:

- Verify if the EC2 instance exists.
- If the instance does not exist, create and run it.
- If the instance exists, check its state:
  - If running, log the current state and skip creation.
  - If stopped, start the instance.
